item_insight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import (show_item, create_product, 
                        show_xml, show_json, show_xml_by_id, show_json_by_id, 
                        register,  login_user, logout_user, add_amount, decrease_amount, edit_product, remove_items,
                        get_product_json, add_product_ajax, create_product_flutter, show_json_by_user)

app_name = 'main'

urlpatterns = [
    path('', show_item, name='show_item'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout'),
    path('add-amount/<int:item_id>/', add_amount, name='add_amount'),
    path('decrease-amount/<int:item_id>/', decrease_amount, name='decrease_amount'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-product-ajax/<int:item_id>/', remove_items, name='remove_items'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json-by-user/',show_json_by_user, name='show_json_by_user'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ItemStore(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()   
    price = models.BigIntegerField()
    category = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import ItemStore

class ProductForm(ModelForm):
    class Meta:
        model = ItemStore
        fields = ["name", "amount", "price", "category", "description"]

main/views.py
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from main.models import ItemStore
from django.urls import reverse
from django.shortcuts import render

#Tugas 4
import datetime
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt


import json

# Create your views here.
@login_required(login_url='/login')
def show_item(request):
    items = ItemStore.objects.filter(user=request.user)
    context = {
        'name': request.user.username,
        'creator' : 'Shanti Yoga Rahayu',
        'id' : 2206082360,
        'class' : 'PBP D',
        'items_list': items,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, 'main.html', context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_item'))
    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = ItemStore.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ItemStore.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ItemStore.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ItemStore.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def add_amount(request, item_id):
    if request.method == 'POST':
        item = ItemStore.objects.get(pk=item_id)
        item.user = request.user
        if item.amount > 0:
            item.amount += 1
            item.save()
        return HttpResponse(b"ADDED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def decrease_amount(request, item_id):
    if request.method == 'POST':
        item = ItemStore.objects.get(pk=item_id)
        item.user = request.user
        if item.amount > 1:
            item.amount -= 1
            item.save()
        else:
            item.delete()
        return HttpResponse(b"REDUCED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def remove_items(request, item_id):
    if request.method == "DELETE":
        item = ItemStore.objects.get(pk=item_id, user=request.user)
        item.delete()
        return HttpResponse(b"DELETED", status=201)
    
    return HttpResponseNotFound()

def edit_product(request, id):
    product = ItemStore.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_item'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = ItemStore.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        price = request.POST.get("price")
        category = request.POST.get("category")
        user = request.user

        new_product = ItemStore(name=name, amount=amount, description=description, price=price, category=category, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_item")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = ItemStore.objects.create(
            user = request.user,
            name = data["name"],
            category = data['category'],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
def show_json_by_user(request):
    data = ItemStore.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        font-family: 'Poppins', sans-serif;
        background-image: url(https://getwallpapers.com/wallpaper/full/e/a/9/1227331-pink-laptop-wallpapers-1920x1080-for-desktop.jpg);
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .create_product {
        width: 360px;
        background-color: rgba(255, 255, 255, 0.3);
        padding: 20px;
        border-radius: 20px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
    }

    h1 {
        color: #cb0073;
        text-align: center;
    }

    td {
        padding: 10px;
    }

    td.label {
        color: #a90c65;
        font-weight: bold;
    }

    input[type="text"],
    input[type="submit"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #F91C9B;
        border-radius: 10px;
        font-family: 'Poppins', sans-serif;
        color: #88094f;
    }

    input[type="submit"] {
        background-color: #F91C9B;
        color: #fff;
        cursor: pointer;
        width: auto; 
        padding: 10px 20px; 
    }

    input[type="submit"]:hover {
        background-color: #c7107e;
    }

    .error-message {
        color: rgb(149, 6, 80);
        font-size: 12px;
        display: none;
        margin-top: 5px; 
    }
 
    .button-container {
        align-items: center;
        margin: 0 auto; 
        display: block; 
        margin-top: 10px;
    }
</style>

<script>
    function validateNumericInput(inputField, errorMessageId) {
        const inputValue = inputField.value;
        if (!/^\d+(\.\d+)?$/.test(inputValue)) {
            document.getElementById(errorMessageId).style.display = 'block';
            inputField.value = '';
            inputField.focus();
        } else {
            document.getElementById(errorMessageId).style.display = 'none';
        }
    }
</script>

<div class="create_product">

    <h1>Add New Item</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">Name Item: </td>
                <td><input type="text" name="name" class="form-control"></td>
            </tr>
            <tr>
                <td class="label">Amount: </td>
                <td>
                    <input type="text" name="amount" class="amount" onblur="validateNumericInput(this, 'amountError')">
                    <p id="amountError" class="error-message">Amount must be a numeric value.</p>
                </td>
            </tr>
            <tr>
                <td class="label">Price: </td>
                <td>
                    <input type="text" name="price" class="price" onblur="validateNumericInput(this, 'priceError')">
                    <p id="priceError" class="error-message">Price must be a numeric value.</p>
                </td>
            </tr>
            <tr>
                <td class="label">Category: </td>
                <td><input type="text" name="category" class="form-control"></td>
            </tr>
            <tr>
                <td class="label">Description: </td>
                <td><input type="text" name="description" class="form-control"></td>
            </tr>
            <tr>
                <td></td>
                <td class="button-container">
                    <input class="btn createproduct_button" type="submit" value="Add Item">
                </td>
            </tr>
        </table>
    </form>

</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Edit Product</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        font-family: 'Poppins', sans-serif;
        background-image: url(https://getwallpapers.com/wallpaper/full/e/a/9/1227331-pink-laptop-wallpapers-1920x1080-for-desktop.jpg);
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .edit-product {
        background-color: rgba(255, 255, 255, 0.3);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
    }

    h1 {
        color: #F91C9B;
        text-align: center;
    }

    table {
        margin: 0 auto;
    }

    td {
        padding: 10px;
    }

    td.label {
        color: #a90c65;
        font-weight: bold;
    }

    input[type="text"] {
        width: 80%;
        padding: 10px;
        border: 1px solid #F91C9B;
        border-radius: 10px;
        font-family: 'Poppins', sans-serif;
        color: #88094f;
    }

    input[type="submit"] {
        background-color: #F91C9B;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 10px;
        cursor: pointer;
        font-family: 'Poppins', sans-serif;
    }

    input[type="submit"]:hover {
        background-color: #c7107e;
    }
</style>

<script>
    function validateNumericInput(inputField, errorMessageId) {
        const inputValue = inputField.value;
        if (!/^\d+(\.\d+)?$/.test(inputValue)) {
            document.getElementById(errorMessageId).style.display = 'block';
            inputField.value = '';
            inputField.focus();
        } else {
            document.getElementById(errorMessageId).style.display = 'none';
        }
    }
</script>

<div class="edit-product">
    <h1>Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">Name Item: </td>
                <td><input type="text" name="name" class="form-control" value="{{ form.name.value }}">
                </td>
            </tr>
            <tr>
                <td class="label">Amount: </td>
                <td>
                    <input type="text" name="amount" class="amount" onblur="validateNumericInput(this, 'amountError')" value="{{ form.amount.value }}">
                    <p id="amountError" class="error-message">Amount must be a numeric value.</p>
                </td>
            </tr>
            <tr>
                <td class="label">Price: </td>
                <td>
                    <input type="text" name="price" class="price" onblur="validateNumericInput(this, 'priceError')" value="{{ form.price.value }}">
                    <p id="priceError" class="error-message">Price must be a numeric value.</p>
                </td>
            </tr>
            <tr>
                <td class="label">Category: </td>
                <td><input type="text" name="category" class="form-control" value="{{ form.category.value }}">
                </td>
            </tr>
            <tr>
                <td class="label">Description: </td>
                <td><input type="text" name="description" class="form-control" value="{{ form.description.value }}">
                </td>
            </tr>
            <tr>
                <td></td>
                <td class="button-container">
                    <input class="btn createproduct_button" type="submit" value="Edit Product">
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        font-family: 'Poppins', sans-serif;
        background-image: url(https://getwallpapers.com/wallpaper/full/e/a/9/1227331-pink-laptop-wallpapers-1920x1080-for-desktop.jpg);
        background-size: cover; 
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .login {
        background-color: rgba(255, 255, 255, 0.3); 
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
    }

    h1 {
        color: #F91C9B;
        text-align: center;
    }

    table {
        margin: 0 auto;
    }

    td {
        padding: 10px;
    }

    td.label {
        color: #a90c65;
        font-weight: bold;
    }

    input[type="text"],
    input[type="password"] {
        width: 90%;
        padding: 10px;
        border: 1px solid #F91C9B; 
        border-radius: 10px;
        font-family: 'Poppins', sans-serif; 
        color: #88094f;
    }

    .login_btn {
        background-color: #F91C9B; 
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 10px;
        cursor: pointer;
        font-family: 'Poppins', sans-serif; 
    }

    .login_btn:hover {
        background-color: #c7107e; 
    }

    ul {
        list-style: none;
        padding: 0;
    }

    li {
        color: #78194f; 
        font-size: 12px;
    }

    a {
        color: #F91C9B; 
        font-family: 'Poppins', sans-serif;

    }
</style>

<div class="login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td class="label">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        
    <p style="font-size: 14px;">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
  <title>Item Insight Page</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script src="{% static 'js/main.js' %}"></script>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

  <style>
    * {
        font-family: 'Poppins', sans-serif;
        cursor: pointer;
    }

    body {
    background-image: url(https://getwallpapers.com/wallpaper/full/e/a/9/1227331-pink-laptop-wallpapers-1920x1080-for-desktop.jpg);
    background-attachment: fixed; /* Menjadikan gambar latar belakang tetap */
    background-size: cover; /* Mengisi seluruh latar belakang */
    margin-top: 25px;
    text-align: center;
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
    }

    .data-app {
        font-family: 'Poppins', sans-serif;
        font-size: 14px;
        line-height: 1.2; 
        color: #8a093c;
        margin: 1rem 1rem 1rem 0.5rem;
    }

    .item-name {
        font-size: 3rem;
        font-weight: 700;
        color: rgb(232, 38, 157);
        margin: 1rem 1rem 1rem 0.5rem;
        text-align: left;
    }

    .item-name span {
        color: rgb(95, 8, 76);
    }

    .header-controls {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
    }

    .logout-button {
        background-color: rgb(167, 28, 93);
        color: rgb(255, 255, 255);
        font-weight: bold;
        border: 2px solid rgb(255, 255, 255);
        border-radius: 10px;
        padding: 5px 20px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .logout-button:hover {
        background-color: rgb(125, 5, 63);
    }

    .item-count {
        background-color: rgba(255, 255, 255, 0.5);
        color: rgb(156, 0, 94);
        font-weight: bold;
        border: 2px solid #581c4e;
        border-radius: 10px;
        padding: 20px 20px;
        margin: 20px auto;
        max-width: 500px;
        text-align: center;
    }

    .item-count p {
        margin: 0;
    }

    .add-product {
        margin-top: 60px;
        margin-bottom: 60px;
    }

    .pos {
        display: flex;
        justify-content: center;
    }
    
    .card-container {
        flex-wrap: wrap;
        justify-content: space-around;
        margin: 0 auto;
        gap: 20px;
        max-width: 1200px;
    }

    .col-3 {
        flex: 0 0 33.33%;
        max-width: 33.33%;
        box-sizing: border-box;
        padding: 15px;
    }

    .product-card {
        border: 1px solid #ddd;
        padding: 15px;
        margin: 0 auto;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s;
        width: 100%;
        position: relative;
        background-color: rgba(255, 255, 255, 0.5);
    }

    .col-3:last-child .product-card {
        background-color: rgb(255, 168, 216);
    }

    .product-card:hover {
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
    }

    .amount-controls {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 5px;
    }

    .btn-edit {
        background: none;
        border: none;
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 1.5rem;
        cursor: pointer;
    }
    
    .btn-add {
        background-color: rgba(239, 12, 125, 0.733);
        color: rgb(255, 255, 255);
        font-weight: bold;
        border: 1px solid rgb(220, 56, 138);
        border-radius: 5px;
        padding: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-decrease {
        background-color: rgb(182, 22, 126);
        color: rgb(255, 255, 255);
        font-weight: bold;
        border: 2px solid rgb(182, 22, 126);
        border-radius: 5px;
        padding: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-remove {
        background-color: rgb(137, 18, 94);
        color: rgb(255, 255, 255);
        font-weight: bold;
        border: 1px solid rgb(137, 18, 94);
        border-radius: 5px;
        padding: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-add:hover {
        background-color: #5e1240; 
    }

    .btn-decrease:hover {
        background-color: #5e1240; 
    }

    .btn-remove:hover {
        background-color: #5e1240; 
    }

    .category {
        color: #df048b;
    }
    

  </style>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="header">
                <h1 class="item-name">
                    Item <span> Insight</span>
                </h1>
                <div class="header-controls">
                    <div class="last-login">
                        <h4>Sesi terakhir login: {{ last_login }}</h4>
                    </div>
                    <a href="{% url 'main:logout' %}">
                        <button class="logout-button">Logout</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="data-app-container">
        <div class="data-app">
            <h3>{{ creator }}</h3>
            <h3>{{ id }}</h3>
            <h3>{{ class }}</h3>
        </div>
    </div>
    

    <div class="row">
      <div class="col-12">
          <div class="item-count">
              <p id="ItemCount"></p>
          </div>
      </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div id="product_card"></div>
        </div>
    </div>

    <div class="pos">
      <div class="row card-container">
        <!-- Kode JavaScript akan menempatkan kartu produk di sini -->
      </div> 
    </div> 

    <div class="row">
      <div class="col-12 text-center">
        <button type="button" class="btn btn-primary add-product" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color: rgb(173, 3, 114); border-color: rgb(173, 3, 114);">Add Item by AJAX</button>
      </div>
    </div>
</div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" onsubmit="return false;">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="name" class="col-form-label">Name:</label>
                      <input type="text" class="form-control" id="name" name="name"></input>
                  </div>
                  <div class="mb-3">
                    <label for="category" class="col-form-label">Category:</label>
                    <input type="text" class="form-control" id="category" name="category"></input>
                  </div>
                  <div class="mb-3">
                    <label for="amount" class="col-form-label">Amount:</label>
                    <input type="number" class="form-control" id="amount" name="amount"></input>
                  </div>
                  <div class="mb-3">
                      <label for="price" class="col-form-label">Price:</label>
                      <input type="number" class="form-control" id="price" name="price"></input>
                  </div>
                  <div class="mb-3">
                      <label for="description" class="col-form-label">Description:</label>
                      <textarea class="form-control" id="description" name="description"></textarea>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
          </div>
      </div>
  </div>
</div>

<script>
  async function getProducts() {
    return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
    document.getElementById("product_card").innerHTML = ""
    const products = await getProducts()
    const itemCount = document.getElementById("ItemCount");
    const totalItem = products.length;
    itemCount.innerHTML = `Exquisite collection of ${totalItem} floral item(s) stored in this app`
    
    let htmlString = ``
    products.forEach((item) => {
    htmlString += `
      <div class="col-3">
        <div class="product-card">
            <h3>${item.fields.name}</h3>
            <a href="edit-product/${item.pk}">
              <button class="btn-edit">✏️</button>
            </a>
            <p>Amount: ${item.fields.amount}</p>
            <p>Description: ${item.fields.description}</p>
            <p>Price: IDR ${item.fields.price}</p>
            <p class="category">Category: ${item.fields.category}</p>
            <div class="card-footer">
                <button onclick="addAmount(${item.pk})" class="btn-add">Add</button>
                <button onclick="decreaseAmount(${item.pk})" class="btn-decrease">Decrease</button>
                <button onclick="removeItem(${item.pk})" class="btn-remove">Remove</button>
            </div>
          </div>
      </div>`;
    })

    document.querySelector(".card-container").innerHTML = htmlString;
  }

  function addProduct() {
      fetch("{% url 'main:add_product_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshProducts)

      document.getElementById("form").reset()
      return false
  }

  function addAmount(itemId) {
    fetch(`add-amount/${itemId}/`, {
          method: "POST",
      }).then(refreshProducts)

      return false
  }

  function decreaseAmount(itemId) {
    fetch(`decrease-amount/${itemId}/`, {
          method: "POST",
      }).then(refreshProducts)

      return false
  }

  function removeItem(itemId) {
    fetch(`delete-product-ajax/${itemId}/`, {
          method: "DELETE",
      }).then(refreshProducts)

      return false
  }
  
  refreshProducts()
  
  document.getElementById("button_add").onclick = addProduct
</script>

{% endblock content %}